version: '3'
services:
  db:
    hostname: db
    image: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: soccer
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3333:3306
    restart: always
  api:
    build: .
    hostname: soccer
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3333
      WAIT_BEFORE_HOSTS: 80
    links:
      - db:db
