spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    time-zone: UTC
logging:
  config: classpath:logs/logback-spring.xml
mail:
  config:
    host: smtp.gmail.com
    port: 587
    address: praktyki2019tt@gmail.com
    password:
server:
  default:
    timezone: UTC
  servlet:
    context-path: /api
jwt:
  app:
    jwtSecret: uCYXW(/H!5pYIX`~.wlKOVh/Y|2gmO
    jwtExpirationInMs: 1209600000
properties:
  account:
    active:
      file-name: active
      link: /login?activeKey=
      mail:
        subject: Confirm your register in soccker.
    change:
      password:
        file-name: change_password
        link: /change-password?changePasswordKey=
        mail:
          subject: Change your password in soccker.
      email:
        file-name: change_email
        link:
          main: /change-data?
          param1: "newEmail="
          param2: "&changeEmailKey="
        mail:
          subject: Confirm the change of email address.

