server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:soccer
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    change-log: classpath:db/master-test.xml
