spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    time-zone: UTC
logging:
  config: classpath:logs/logback-spring.xml
mail:
  config:
    host: smtp.gmail.com
    port: 587
    address: praktyki2019tt@gmail.com
    password:
server:
  default:
    timezone: UTC
  servlet:
    context-path: /api
jwt:
  app:
    jwtSecret: uCYXW(/H!5pYIX`~.wlKOVh/Y|2gmO
    jwtExpirationInMs: 1209600000
docs:
  path:
    mail:
      active: src/main/resources/docs/mail/active.html
      confirm: src/main/resources/docs/mail/confirmationOfReservation.html
account:
  confirm:
    link: http://localhost:4200/login?activeToken=
    mail:
      subject: Confirm your register in soccer.

reservation:
  confirm:
    link: http://localhost:4200/confirmation?activeToken=
    mail:
      subject: Confirm your reservation in soccer